In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/lending_club_scaled_ml.csv')

from sklearn.model_selection import train_test_split

X = df.drop(['grade'],axis= 1)
y = df.grade


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [3]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


def scoring(x, y, clf):

    print(confusion_matrix(y, clf.predict_classes(x)))
    print(classification_report(y, clf.predict_classes(x)))

In [4]:
import tensorflow as tf

x_len = len(X.columns)

some_activation = tf.keras.layers.LeakyReLU(alpha=0.3)

model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(x_len, activation=some_activation, input_shape=(x_len,)))
model.add(tf.keras.layers.Dense(1000, activation=some_activation))
model.add(tf.keras.layers.Dense(2000, activation=some_activation))
model.add(tf.keras.layers.Dense(2000, activation=some_activation))
model.add(tf.keras.layers.Dense(2500, activation=some_activation))
model.add(tf.keras.layers.Dense(7, activation='sigmoid'))

model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy',metrics=['accuracy','categorical_accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
for number in range(10):
    print('Set #%s' %number)
    model.fit(X_train, y_train, validation_split=0.25, epochs=10)
    scoring(X_test,y_test,model)

Set #0
Train on 1259635 samples, validate on 419879 samples
Epoch 1/10
1259635/1259635 [==============================] - 266s 211us/sample - loss: 0.7953 - acc: 0.6536 - categorical_accuracy: 0.1674 - val_loss: 0.6751 - val_acc: 0.7072 - val_categorical_accuracy: 0.2060
Epoch 2/10
1259635/1259635 [==============================] - 262s 208us/sample - loss: 0.4966 - acc: 0.7807 - categorical_accuracy: 0.1737 - val_loss: 0.4465 - val_acc: 0.8036 - val_categorical_accuracy: 0.1903
Epoch 3/10
1259635/1259635 [==============================] - 262s 208us/sample - loss: 0.4354 - acc: 0.8058 - categorical_accuracy: 0.1751 - val_loss: 0.4237 - val_acc: 0.8121 - val_categorical_accuracy: 0.1367
Epoch 4/10
1259635/1259635 [==============================] - 261s 207us/sample - loss: 0.4041 - acc: 0.8193 - categorical_accuracy: 0.1760 - val_loss: 0.4602 - val_acc: 0.7986 - val_categorical_accuracy: 0.1609
Epoch 5/10
1259635/1259635 [==============================] - 260s 207us/sample - loss: 0.38

Epoch 10/10
1259635/1259635 [==============================] - 260s 207us/sample - loss: 0.2787 - acc: 0.8730 - categorical_accuracy: 0.1763 - val_loss: 0.2777 - val_acc: 0.8741 - val_categorical_accuracy: 0.1735
[[132920   9523     11      0      0      0      0]
 [  9080 215169  17110      6      0      0      0]
 [   375  15662 207724  11229     16      4      0]
 [   184     63   9690 109262   4405     12      0]
 [   167      8     78  14906  40785   2732      1]
 [    71      5      5    137   3859  16319     11]
 [    10      0      0      2     42   5610     31]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93    142454
           1       0.89      0.89      0.89    241365
           2       0.89      0.88      0.88    235010
           3       0.81      0.88      0.84    123616
           4       0.83      0.70      0.76     58677
           5       0.66      0.80      0.72     20407
           6       0.72      0.01      0.01

1259635/1259635 [==============================] - 247s 196us/sample - loss: 0.2101 - acc: 0.9043 - categorical_accuracy: 0.1757 - val_loss: 0.2596 - val_acc: 0.8855 - val_categorical_accuracy: 0.1846
Epoch 2/10
1259635/1259635 [==============================] - 240s 190us/sample - loss: 0.2090 - acc: 0.9046 - categorical_accuracy: 0.1757 - val_loss: 0.2709 - val_acc: 0.8834 - val_categorical_accuracy: 0.1767
Epoch 3/10
1259635/1259635 [==============================] - 242s 192us/sample - loss: 0.2070 - acc: 0.9056 - categorical_accuracy: 0.1759 - val_loss: 0.2639 - val_acc: 0.8861 - val_categorical_accuracy: 0.1724
Epoch 4/10
1259635/1259635 [==============================] - 241s 192us/sample - loss: 0.2056 - acc: 0.9060 - categorical_accuracy: 0.1757 - val_loss: 0.2884 - val_acc: 0.8780 - val_categorical_accuracy: 0.1835
Epoch 5/10
1259635/1259635 [==============================] - 237s 188us/sample - loss: 0.2051 - acc: 0.9063 - categorical_accuracy: 0.1758 - val_loss: 0.2840 - va